package com.digivive.api.entity;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "person")
public class Person implements Serializable {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "personId")
    private String personId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String age;

    public String getPersonId() {
        return personId;
    }

    public void setPersonId(String personId) {
        this.personId = personId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return "Person [personId=" + personId + ", name=" + name + ", age=" + age + "]";
    }

    public Person(String personId, String name, String age) {
        super();
        this.personId = personId;
        this.name = name;
        this.age = age;
    }

    public Person() {
        super();
    }
}
